repos:
  - repo: local
    hooks:
      - id: Lint
        name: Lint
        language: system
        entry: pylint --rcfile=.pylintrc crawler  app
        pass_filenames: false
        always_run: true