repos:
  - repo: local
    hooks:
      - id: E2E.
        name: E2E.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: ./scripts/startup.sh test

