repos:
  - repo: local
    hooks:
      - id: create_reports.
        name: create_reports.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: touch pytest-results.xml

      - id: assign_right_reports.
        name: assign_right_reports.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: chmod 777 pytest-results.xml

      - id: stop_everything.
        name: stop_everything.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose down

      - id: start_database.
        name: start_database.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up --build -d mysql mysql

      - id: build_image.
        name: build_image.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose build

      - id: initialize_database.
        name: initialize_database.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up --build --exit-code-from initialize_database initialize_database

      - id: run_unit_tests.
        name: run_unit_tests.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up --build --exit-code-from run_unit_tests run_unit_tests

      - id: manager.
        name: manager.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up -d --build manager

      - id: test_manager.
        name: test_manager.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: curl --retry 30 --retry-all-errors --retry-delay 1 "localhost:6000/"

      - id: worker.
        name: worker.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up --build --exit-code-from worker worker

      - id: build_index.
        name: build_index.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up --build --exit-code-from build_index build_index

      - id: build_metrics.
        name: build_metrics.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: docker-compose up --build --exit-code-from build_metrics build_metrics

      - id: backend_server.
        name: backend_server.
        language: system
        pass_filenames: false
        always_run: true
        entry: docker-compose up --build -d backend_server

      - id: test_api.
        name: test_api.
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        entry: curl --retry 30 --retry-all-errors --retry-delay 1 "localhost:4000/search?q=tubingen"

