repos:
  - repo: local
    hooks:
      - id: Lint
        name: Lint
        language: system
        entry: pylint --rcfile=.pylintrc crawler backend
        pass_filenames: false
        always_run: true