repos:
  - repo: local
    hooks:
      - id: Pre-commit.
        name: Pre-commit.
        language: system
        entry: ./scripts/pre-commit.sh
        pass_filenames: false
        always_run: true