# Docker Compose file for TueSearch

version: '3.9'
services:
  ############################################################
  # Start frontend.
  # Persistent process.
  ############################################################
  frontend_server:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend_server
    depends_on:
      - backend_server
      - mysql
    ports:
      - '5000:5000'
    restart: 'always'
    command: serve -s build -l 5000
    env_file:
      - frontend/.env
    networks:
      - mysql_net
