# Docker Compose file for TueSearch

version: '3'
services:
  ####################################################
  # MySQL database
  ####################################################
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
  ####################################################
  # Initialize database
  ####################################################
  initialize_database:
    build:
      context: .
      dockerfile: python.Dockerfile
    container_name: crawler
    restart: "no"
    command:
      - ls
      - python3 -m crawler.initialize_database
      - python3 -m crawler.crawl -n 10         # Crawl 10 initial documents
    env_file:
      - .env
    volumes:
      - .:/app
      - /opt/tuesearch/log:/opt/tuesearch/log
      - /opt/tuesearch/data:/opt/tuesearch/data
volumes:
  mysql-data: