# Docker Compose file for TueSearch PROD SERVER

version: '3.9'
networks:
  prod_mysql_net:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/24
volumes:
  prod_tuesearch_database:
    external: true
  prod_tuesearch:
    external: true

services:
  ############################################################
  # Nginx Server
  ############################################################
  prod_nginx:
    image: nginx
    container_name: prod_nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./certs:/etc/nginx/certs:ro
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.12
  ############################################################
  # MySQL models
  ############################################################
  prod_mysql:
    image: ghcr.io/tuesearch/search-engine/database-server:latest
    container_name: prod_mysql
    restart: always
    env_file:
      - .env
      - .prod.env
    volumes:
      - prod_tuesearch_database:/var/lib/mysql
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.2
  ############################################################
  # Viewing data
  ############################################################
  prod_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prod_phpmyadmin
    env_file:
      - .env
      - .prod.env
    restart: always
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.3
  ############################################################
  # Initialize models.
  # Feed the models with initial jobs and initial documents.
  # Will run once.
  ############################################################
  prod_initialize_database:
    image: ghcr.io/tuesearch/search-engine/backend-server:latest
    container_name: prod_initialize_database
    restart: 'on-failure'
    command: 'python3 -m scripts.initialize_database'
    env_file:
      - .env
      - .prod.env
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.4
  ############################################################
  # Start manager.
  ############################################################
  prod_manager:
    image: ghcr.io/tuesearch/search-engine/backend-server:latest
    container_name: prod_manager
    restart: 'always'
    command: >
      sh -c "
      pip install gunicorn; 
      /home/tuesearch/.local/bin/gunicorn -w 8 -b 0.0.0.0:6000 crawler.manager.main:app;
      "
    env_file:
      - .env
      - .prod.env
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.5
  ############################################################
  # Start the worker.
  ############################################################
  prod_worker:
    image: ghcr.io/tuesearch/search-engine/backend-server:latest
    container_name: prod_worker
    restart: 'on-failure'
    command: 'python3 -m crawler.worker.main -n 4'
    env_file:
      - .env
      - .prod.env
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.6
  ############################################################
  # Build indexer.
  ############################################################
  prod_build_index:
    image: ghcr.io/tuesearch/search-engine/backend-server:latest
    container_name: prod_build_index
    restart: 'on-failure'
    command: 'python3 -m backend.build_index'
    env_file:
      - .env
      - .prod.env
    volumes:
      - prod_tuesearch:/opt/tuesearch
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.7
  ############################################################
  # Build rankers.
  ############################################################
  prod_build_metrics:
    image: ghcr.io/tuesearch/search-engine/backend-server:latest
    container_name: prod_build_metrics
    restart: 'on-failure'
    command: 'python3 -m backend.build_metrics'
    env_file:
      - .env
      - .prod.env
    volumes:
      - prod_tuesearch:/opt/tuesearch
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.8
  ############################################################
  # Start backend.
  # Persistent process.
  ############################################################
  prod_backend_server:
    image: ghcr.io/tuesearch/search-engine/backend-server:latest
    container_name: prod_backend_server
    restart: 'always'
    command: >
      sh -c "
      pip install gunicorn; 
      /home/tuesearch/.local/bin/gunicorn -w 1 -b 0.0.0.0:4000 backend.app:app;
      "
    env_file:
      - .env
      - .prod.env
    volumes:
      - prod_tuesearch:/opt/tuesearch
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.9
  ############################################################
  # Start frontend.
  # Persistent process.
  ############################################################
  prod_frontend_server:
    image: ghcr.io/tuesearch/search-engine/frontend-server:latest
    container_name: prod_frontend_server
    restart: 'always'
    command: serve -s build -l 5000
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.10
  ############################################################
  # Start Watchtower
  # Watchtower will check for new images every 5 minutes and
  # update the running containers.
  ############################################################
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=500
      - WATCHTOWER_CLEANUP=true
    networks:
      prod_mysql_net:
        ipv4_address: 172.20.0.11
